{{ if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: kube-prometheus
  name: prometheus-envoy
spec:
  selector:
    matchLabels:
      sidecar-gateway: "envoy"
  endpoints:
    - targetPort: envoy-metrics
      interval: 30s
      path: /stats/prometheus
{{ end }}