{{ if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    prometheus: "true" # matches the value added in helm-prometheus.yml
    release: {{ .Release.Name }}
  name: kube-prometheus-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  podMetricsEndpoints:
    - port: envoy-metrics
      interval: 30s
      path: /stats/prometheus
  {{ end }}