apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /grafana
            backend:
              service:
                name: prometheus-grafana
                port:
                  number: 80