apiVersion: v1
kind: Service
metadata:
  name: {{ template "service.fullname" . }}
  labels:
    app: {{ template "service.fullname" . }}
    helm.sh/chart: {{ include "service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: 10000
      name: http
  selector:
    app: {{ template "service.fullname" . }}
    release: {{ .Release.Name }}
