apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.configMap }}
  labels:
    app: {{ template "service.fullname" . }}
    helm.sh/chart: {{ include "service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- (.Files.Glob "config/**").AsConfig | nindent 2 }}
